name: nojcasts
description: "RSS reader for podcasts"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  audioplayers: ^6.1.0
  http: ^1.2.2
  html: ^0.15.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  sqflite: ^2.4.0
  xml: ^6.5.0
  go_router: ^16.0.0
  synchronized: ^3.4.0
  cv: ^1.1.6
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.8.0
  
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/nojcasts_icon_w_background.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/

